export const CONSTRUCTION_SKILLS = [
  "Mason",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Painter",
  "Welder",
  "Tile Worker",
  "Concrete Finisher",
  "Roofer",
  "Drywaller",
  "HVAC Technician",
  "Scaffolder",
  "Excavator Operator",
  "Crane Operator",
  "Steel Fixer",
  "Bricklayer",
  "Glazier",
  "Plasterer",
  "Landscaper",
  "General Laborer",
  "Demolition Expert",
  "Heavy Equipment Operator",
  "Pipefitter",
  "Surveyor",
  "Foreman",
  "Site Manager",
  "Insulation Installer",
  "Paver",
  "Estimator",
  "Safety Inspector",
] as const;

export type ConstructionSkill = typeof CONSTRUCTION_SKILLS[number];
